-- Auto-generated by matugen - DO NOT EDIT
-- These colors are derived from your current wallpaper

return {
  -- Base colors
  surface = "{{colors.surface.default.hex}}",
  surface_dim = "{{colors.surface_dim.default.hex}}",
  surface_container = "{{colors.surface_container.default.hex}}",
  surface_container_high = "{{colors.surface_container_high.default.hex}}",
  on_surface = "{{colors.on_surface.default.hex}}",
  on_surface_variant = "{{colors.on_surface_variant.default.hex}}",

  -- Accent colors
  primary = "{{colors.primary.default.hex}}",
  on_primary = "{{colors.on_primary.default.hex}}",
  secondary = "{{colors.secondary.default.hex}}",
  on_secondary = "{{colors.on_secondary.default.hex}}",
  tertiary = "{{colors.tertiary.default.hex}}",
  on_tertiary = "{{colors.on_tertiary.default.hex}}",

  -- Semantic colors
  error = "{{colors.error.default.hex}}",
  on_error = "{{colors.on_error.default.hex}}",

  -- Derived UI colors (for specific highlights)
  bg_dark = "{{colors.surface_dim.default.hex}}",
  bg_float = "{{colors.surface_container.default.hex}}",
  fg = "{{colors.on_surface.default.hex}}",
  fg_dim = "{{colors.on_surface_variant.default.hex}}",
  accent = "{{colors.primary.default.hex}}",
  accent_dim = "{{colors.secondary.default.hex}}",

  -- RGB values for transparent backgrounds
  surface_rgb = "{{colors.surface.default.red}},{{colors.surface.default.green}},{{colors.surface.default.blue}}",
  primary_rgb = "{{colors.primary.default.red}},{{colors.primary.default.green}},{{colors.primary.default.blue}}",
}
