-- Auto-generated by matugen - DO NOT EDIT
-- These colors are derived from your current wallpaper

return {
  -- Base colors
  surface = "#131313",
  surface_dim = "#131313",
  surface_container = "#1f1f1f",
  surface_container_high = "#2a2a2a",
  on_surface = "#e2e2e2",
  on_surface_variant = "#c6c6c6",

  -- Accent colors
  primary = "#ffafd1",
  on_primary = "#5c113c",
  secondary = "#e1bdca",
  on_secondary = "#412a34",
  tertiary = "#f2bb98",
  on_tertiary = "#49280f",

  -- Semantic colors
  error = "#ffb4ab",
  on_error = "#690005",

  -- Derived UI colors (for specific highlights)
  bg_dark = "#131313",
  bg_float = "#1f1f1f",
  fg = "#e2e2e2",
  fg_dim = "#c6c6c6",
  accent = "#ffafd1",
  accent_dim = "#e1bdca",

  -- RGB values for transparent backgrounds
  surface_rgb = "19,19,19",
  primary_rgb = "255,175,209",
}
